---
layout: issue
title: "Zend_Loader::loadFile() doesn't throw an exception as mentioned when file doesn't exist"
id: ZF-10975
---

ZF-10975: Zend\_Loader::loadFile() doesn't throw an exception as mentioned when file doesn't exist
--------------------------------------------------------------------------------------------------

 Issue Type: Bug Created: 2011-01-21T03:24:09.000+0000 Last Updated: 2011-02-01T09:52:49.000+0000 Status: Resolved Fix version(s): 
 Reporter:  Strict Coding (strictcoding)  Assignee:  Matthew Weier O'Phinney (matthew)  Tags: - Zend\_Loader
 
 Related issues: 
 Attachments: 
### Description

The Zend\_Loader::loadFile() is documented as : @throws Zend\_Exception

But it doesn't throw any exception if the file doesn't exist. Instead, PHP just dies with a fatal error.

This is problematic because we can't catch an exception this way:

try { Zend\_Loader::loadClass('ExampleController'); } catch (Zend\_Exception $e) { ... }

 

 

### Comments

Posted by Ramon Henrique Ornelas (ramon) on 2011-01-22T12:11:42.000+0000

The exception throw is through of the called Zend\_Loader::\_securityCheck() that validates filename.

 

 

Posted by Strict Coding (strictcoding) on 2011-01-22T16:15:52.000+0000

Whilst it indeed validates the file name as being secure, it doesn't check that the file does exist and is readable prior to include it.

Instead, when the class file cannot be found, include() just issues a PHP warning, and no exception is thrown, so we can't catch it to handle this error gracefully!

 

 

Posted by Matthew Weier O'Phinney (matthew) on 2011-01-24T05:01:44.000+0000

In the use case shown in the description, however, you _will_ get an exception, as loadClass() _does_ raise an exception if the class is not found.

We _used_ to throw exceptions within loadFile(). However, it was problematic. In particular, while include will return a boolean false when unable to load the script, if a script is found, and also returns a boolean false, then you get a false negative. This means there is no tried-and-true way to ensure you know whether or not the operation was successful, unless you perform a test against functionality you know the file provides. (This latter is what loadClass() is doing -- it's checking if the class requested is present after a file has been include'd.)

The only meaningful exception we can throw at this time is the security exception for malformed filenames.

 

 

Posted by Strict Coding (strictcoding) on 2011-01-24T07:43:52.000+0000

My mistake, the exception is indeed thrown through the class\_exists() test. However, we still get a PHP warning stating that the file doesn't exist, which breaks the layout in development mode, and fills the log in production mode.

I understand the argument about the return value of include() (although I can't see why a class file would "return false"), so can't we just check if the file is readable prior to include it?

Something like:

function isIncludable($file) { $paths = explode(PATH\_SEPARATOR, get\_include\_path()); foreach ($paths as $path) { if (is\_readable("$path/$file")) return true;  
 } return false; }

 

 

Posted by Matthew Weier O'Phinney (matthew) on 2011-01-24T11:49:03.000+0000

Because that's really, really horrible from a performance perspective. You're guaranteed at least two I/O stat calls for each file you try and load this way -- versus 1 (or 0, if the realpath cache is hit) by include().

I understand your frustration, but with code such as this which executes dozens if not hundreds of times on each request, stat calls get to be an expensive part of the overall process, and negatively impact performance.

For what it's worth, this situation will be fixed for ZF2 -- in fact, it's already fixed in ZF2. However, we can't backport the solution to ZF1 as the solutions are backwards incompatible.

 

 

Posted by Strict Coding (strictcoding) on 2011-02-01T08:18:08.000+0000

Thanks for your answer, Matthew. I just supposed that we could have another function to test that manually, just in case we need it, not for every class.

But eventually I figured out how the PHP warnings can be ignored with a simple @ symbol, and everything's working fine!

try { @ Zend\_Loader::loadClass($controller, $this->getFrontController()->getControllerDirectory()); } catch (Zend\_Exception $e) { // ... }

Maybe these @ could be included in front of the @include and @include\_once in the Zend\_Loader::loadFile() method?

 

 

Posted by Matthew Weier O'Phinney (matthew) on 2011-02-01T09:07:55.000+0000

No. :)

We used to, but it makes it near-impossible to debug when a class has not been found. Instead, users get a "white screen of death" with no useful information about what caused it. By omitting the silence operators, that situation does not occur.

Additionally, error suppression is really, really expensive at the engine level, particularly with the large number of calls to these particular functions within the framework.

Combined, these are excellent reasons _never_ to use error suppression on these methods -- and they are why we don't today.

 

 

Posted by Strict Coding (strictcoding) on 2011-02-01T09:52:49.000+0000

Then I'm looking forward to the ZF2 solution! Because right now, it's difficult to find a graceful solution when writing our own routing code. Keep up the hard work! ;)

 

 