---
layout: issue
title: "Zend_Session error handlers should test current error reporting level (for @-silenced-functions)"
id: ZF-12494
---

ZF-12494: Zend\_Session error handlers should test current error reporting level (for @-silenced-functions)
-----------------------------------------------------------------------------------------------------------

 Issue Type: Bug Created: 2013-01-03T02:22:03.000+0000 Last Updated: 2013-04-05T16:07:04.000+0000 Status: Closed Fix version(s): 
 Reporter:  Claude Duvergier (cduv)  Assignee:  None  Tags: - Zend\_Session
 
 Related issues: 
 Attachments: 
### Description

Somewhere in my code I'm storing a Zend\_Ldap\_Node into Session. I've just upgraded this application from ZF 1.10 to ZF 1.12 and since then I'm getting bq. Uncaught exception 'Zend\_Session\_Exception' with message 'session has already been started by session.auto-start or session\_start()'"

h3. Errors

Call stack is complaining about an already started Session: ||#||Time||Memory||Function||Location|| |1|0.0061|343536|{main}( )|..\\index.php:0| |2|0.2549|11626392|Zend\_Application->run( )|..\\index.php:38| |3|0.2549|11626392|Zend\_Application\_Bootstrap\_Bootstrap->run( )|..\\Application.php:366| |4|0.2552|11626448|Zend\_Controller\_Front->dispatch( ???, ??? )|..\\Bootstrap.php:97| |5|0.4126|15116600|Zend\_Controller\_Plugin\_Broker->preDispatch( ??? )|..\\Front.php:941| |6|0.4162|15164720|Zend\_Controller\_Plugin\_ErrorHandler->preDispatch( ??? )|..\\Broker.php:309| |7|0.4163|15164720|Zend\_Controller\_Plugin\_ErrorHandler->\_handleError( ??? )|..\\ErrorHandler.php:212|

But variables in local scope (#7) (xDebug infos) shows a Zend\_Session\_Exception with a message related to unserialize() and Zend\_Ldap\_Converter::fromLdapUnserialize(): {quote} Zend\_Session::start() - D:\_ Libraries\\Zend Framework 1.12.1\\library\\Zend\\Ldap\\Converter.php(Line:395): Error #8 unserialize() [](http://php.net/manual/language.operators.errorcontrol.php)<function.unserialize>]: Error at offset 0 of 174474 bytes D:\_ Libraries\\Zend Framework 1.12.1\\library\\Zend\\Ldap\\Converter.php(Line:395): Error #8 unserialize() [<function.unserialize>]: Error at offset 0 of 174474 bytes D:\_ Libraries\\Zend Framework 1.12.1\\library\\Z'... {quote}

h3. Code analysis

After some deep tests I've determined that the error handlers that Zend\_Session::start() uses (namely Zend\_Session\_Exception::handleSessionStartError() are _fired_ when Zend\_Ldap\_Converter::fromLdapUnserialize() tries to unserialize a value despite the whole unserialize-failure management in place (_id._ ignoring unserialize() error messages with the @ error control operator). Then a Zend\_Session\_Exception is thrown by Zend\_Session::start() with the Zend\_Session\_Exception::$sessionStartError message that unserialize() sent.

h3. Reproduction code

With LDAP involved, I thought it would be hard to reproduce, but the problem would occurs anytime a _@-silenced_ function/method called during Zend\_Session is in error. I've set up a whole new ZF project with ZF CLI Tool and tried to reproduce the scenario as simply as possible using a model implementing \_\_wakeup() and a Zend\_Controller\_Action to test it. See code on Gist: <https://gist.github.com/4440257>

h3. Fix proposal

According to [_Error Control Operators_ PHP documentation, custom error handlers are expected to be called in such cases, but [error\_reporting()](http://php.net/manual/function.error-reporting.php) can be used to test if the error was supposed to be ignored (was preceded by @).

See patch proposal on Gist: <https://gist.github.com/4440268>

 

 

### Comments

Posted by Claude Duvergier (cduv) on 2013-01-03T02:31:21.000+0000

Added gist link to reproduction code and fix proposal.

 

 

Posted by Claude Duvergier (cduv) on 2013-01-03T13:32:32.000+0000

As advised on IRC channel #zftalk.dev, a possible workaround is to silence the Zend\_Session Exception itself by calling Zend\_Session::setOptions(array('throw\_startup\_exceptions' => 0)) prior to any Zend\_Session::start().

 

 

Posted by Ralph Schindler (ralph) on 2013-04-05T16:07:04.000+0000

This issue has been closed on Jira and moved to GitHub for issue tracking. To continue following the resolution of this issues, please visit: <https://github.com/zendframework/zf1/issues/44>

 

 