---
layout: issue
title: "Trying to log to multiple loggers raises exeption"
id: ZF-270
---

ZF-270: Trying to log to multiple loggers raises exeption
---------------------------------------------------------

 Issue Type: Bug Created: 2006-07-19T03:36:08.000+0000 Last Updated: 2007-07-05T14:43:15.000+0000 Status: Resolved Fix version(s): - 0.9.2 (06/Apr/07)
 
 Reporter:  Sergey Belov (arikon)  Assignee:  Bill Karwin (bkarwin)  Tags: - Zend\_Log
 
 Related issues: - [ZF-271](/issues/browse/ZF-271)
 
 Attachments: - [ZF-270.patch](/issues/secure/attachment/10081/ZF-270.patch)
 
### Description

Trying to log such this

 
    <pre class="highlight">
    Zend_Log::log('Log text here', Zend_Log::LEVEL_DEBUG, array('File', 'Console'));


raises exeption {panel} Fatal error: Uncaught exception 'Zend\_Log\_Exception' with message 'No instance of log named "Array"' in w:\\usr\\svn\_libs\\zend\\library\\Zend\\Log.php:178 Stack trace: #0 w:\\usr\\svn\_libs\\zend\\library\\Zend\\Log.php(337): Zend\_Log::\_getInstance(Array) #1 w:\\usr\\svn\_libs\\zend\\library\\Zend\\Log.php(405): Zend\_Log::getFields(Array) #2 w:\\home\\framework\\www\\index.php5(58): Zend\_Log::log('Total queries: ...', 1, Array) #3 {main} thrown in w:\\usr\\svn\_libs\\zend\\library\\Zend\\Log.php on line 178 {panel}

 

 

### Comments

Posted by Keith Pope (mute) on 2006-07-29T12:14:22.000+0000

I have attached a patch to resolve this issue.

 

 

Posted by Bill Karwin (bkarwin) on 2006-11-28T17:54:54.000+0000

Scheduling for release 0.8.0.

 

 

Posted by Bill Karwin (bkarwin) on 2007-03-19T16:00:18.000+0000

Assign to Bill Karwin for verification that these issues are resolved by the new Zend\_Log redesign.

 

 

Posted by Bill Karwin (bkarwin) on 2007-04-06T19:11:04.000+0000

The new Zend\_Log architecture supports registering multiple loggers. See documentation for details.

Issue has a solution as of revision 4412.

 

 