---
layout: issue
title: "Nonexistent method used in catch-blocks in code examples"
id: ZF-2384
---

ZF-2384: Nonexistent method used in catch-blocks in code examples
-----------------------------------------------------------------

 Issue Type: Docs: Problem Created: 2008-01-04T18:18:55.000+0000 Last Updated: 2012-03-28T02:13:34.000+0000 Status: Resolved Fix version(s): - 1.7.0 (17/Nov/08)
 
 Reporter:  Martin Mayer (martin.mayer)  Assignee:  Satoru Yoshida (satoruyoshida)  Tags: - Zend\_Gdata
 
 Related issues: 
 Attachments: 
### Description

There's usage of nonexistent method Zend\_Gdata\_App\_Exception::getResponse() in catch blocks in code examples several times in _15.4. Using Google Calendar_ and _15.10. Using Picasa Web Albums_.

 
    <pre class="highlight">
    try {
        ...
    } catch (Zend_Gdata_App_Exception $e) {
        echo "Error: " . $e->getResponse();
    }


Suppose it should be $e->getMessage() method or Zend\_Gdata\_App\_HttpException class which contains getResponse().

 

 

### Comments

Posted by Wil Sinclair (wil) on 2008-01-15T17:05:12.000+0000

Updating to follow documentation issue standards.

 

 

Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2008-09-01T00:50:32.000+0000

Solved in SVN r11174. Zend\_Gdata\_Calender.xml and Zend\_Gdata\_Photos.xml in documentation/en/module\_specs.

 

 

Posted by Wil Sinclair (wil) on 2008-11-13T14:10:18.000+0000

Changing issues in preparation for the 1.7.0 release.

 

 