---
layout: issue
title: "CLONE -Zend_Loader improperly tries to load class &quot;parent&quot;"
id: ZF-5026
---

ZF-5026: CLONE -Zend\_Loader improperly tries to load class "parent"
--------------------------------------------------------------------

 Issue Type: Bug Created: 2008-11-22T10:13:24.000+0000 Last Updated: 2009-11-08T00:30:17.000+0000 Status: Resolved Fix version(s): 
 Reporter:  Kevin Peno (kevin.peno)  Assignee:  Matthew Weier O'Phinney (matthew)  Tags: - Zend\_Loader
 
 Related issues: 
 Attachments: 
### Description

<http://framework.zend.com/issues/browse/ZF-4781>

I think you misunderstand. The only way to call the parent class in that case (without eval because the arguments are variable) is to use the call\_user\_func\_array function in the fashion I mentioned. However, Zend::Loader improperly tries to load a class named "parent" in the process. REGARDLESS of the Zend::Loader call, the parent::find() function WORKS and calls the parent as it should.

Warning: Zend\_Loader::include\_once(parent.php): failed to open stream: No such file or directory in \\Zend\\Loader.php on line 83 Warning: Zend\_Loader::include\_once(): Failed opening 'parent.php' for inclusion (include\_path='.;C:\\inetpub\\PHP\\5.2.6\\pear;C:\\Inetpub\\PHP\\5.2.6\\PEAR\\') in \\Zend\\Loader.php on line 83

Example class:

class MyTable extends Zend\_Db\_Table\_Abstract { public function find() { $args = func\_get\_args(); $r = call\_user\_func\_array( array( $this, 'parent::find' ), $args ); return $r->current(); } }

However, the call does not fail and the result is returned properly from the parent "find" function.

 

 

### Comments

Posted by Matthew Weier O'Phinney (matthew) on 2008-11-22T10:57:46.000+0000

Again, the issue is a PHP one. PHP is seeing "parent" and thinking it needs to load a class -- and, since you have autoloading on, it attempts to do so. The warning you see is a normal one that should occur when the file it's looking for does not exist.

Meanwhile, PHP then merrily dereferences parent to the appropriate object.

This is behavior that needs to be corrected at the PHP level, not the framework level.

 

 

Posted by Matthew Weier O'Phinney (matthew) on 2008-11-22T10:58:01.000+0000

Upstream issue.

 

 

Posted by Andrew Sharpe (andrewsharpe79) on 2009-11-07T23:51:13.000+0000

While the issue may be upstream it would be useful to provide a workaround that we can use in the meantime. The OP says that the call succeeds but I'm having trouble with this in a PHPUnit environment when Zend\_Loader fails to include the file, causing an error in my test.

I cannot find a way to override find and have parent::find called successfully in a testing environment, any pointers appreciated (even RTFM with a reference to the M!).

 

 

Posted by Andrew Sharpe (andrewsharpe79) on 2009-11-08T00:30:17.000+0000

Workaround: use '@' to suppress warnings

$args = func\_get\_args(); @call\_user\_func\_array(array($this, 'parent::find'), $args);

 

 