---
layout: issue
title: "Zend_Validate_Db_Abstract-&gt;_query() throws an error when used with Oracle"
id: ZF-7426
---

ZF-7426: Zend\_Validate\_Db\_Abstract->\_query() throws an error when used with Oracle
--------------------------------------------------------------------------------------

 Issue Type: Bug Created: 2009-07-30T20:11:09.000+0000 Last Updated: 2009-07-31T05:05:19.000+0000 Status: Closed Fix version(s): 
 Reporter:  Adam George (asgeo1)  Assignee:  Ryan Mauger (bittarman)  Tags: - Zend\_Validate
 
 Related issues: 
 Attachments: 
### Description

I found a bug in Zend\_Validate\_Db\_Abstract, which is used by the Zend\_Validate\_Db\_RecordExists validator. The bug occurs when using an Oracle database. Not sure if other other databases are affected.

Line 115 in Zend\_Validate\_Db\_Abstract:

->columns($this->\_field)

This line isn't needed, as the code is selecting \* from the table anyway.

What happens is that Oracle complains because the code is selecting the same column name twice, and there is no any use of an alias to distinguish the duplicate columns:

Oracle error:

 
    <pre class="highlight"> 
    ORA-00918: column ambiguously defined 
    
    SELECT z2.* FROM ( SELECT z1.**, ROWNUM AS "zend_db_rownum" 
    FROM ( SELECT "USERS".*, "USERS"."USERNAME" FROM "USERS" WHERE ("USERNAME" = 'MYUSERNAME') ) z1 ) z2 
    WHERE z2."zend_db_rownum" BETWEEN 1 AND 1


Steps to reproduce:

 
    <pre class="highlight"> 
            /*Just use the validator as normal - it always throws the error*/
            $username = new Zend_Form_Element_Text('username');
            $username->addValidator(
                          'Db_RecordExists',
                          false,
                          array(
                              'USERS', 'USERNAME'
                          )
                      );


 

 

### Comments

Posted by Ryan Mauger (bittarman) on 2009-07-31T01:06:28.000+0000

The columns call is no longer in Zend\_Validate\_Db\_Abstract,

This was fixed in 1.8.4

 

 

Posted by Adam George (asgeo1) on 2009-07-31T05:05:13.000+0000

Thanks Ryan. I must not have noticed the fix when I upgraded to 1.8.4

 

 