---
layout: issue
title: "Zend_Controller_Response_Abstract::sendHeaders()"
id: ZF-832
---

ZF-832: Zend\_Controller\_Response\_Abstract::sendHeaders()
-----------------------------------------------------------

 Issue Type: Bug Created: 2007-01-31T05:28:43.000+0000 Last Updated: 2007-07-05T14:43:43.000+0000 Status: Resolved Fix version(s): - 0.8.0 (21/Feb/07)
 
 Reporter:  Patrick MÃ¼ller (elias)  Assignee:  Matthew Weier O'Phinney (matthew)  Tags: - Zend\_Controller
 
 Related issues: 
 Attachments: 
### Description

related to trunk revision 3058!

Zend\_Controller\_Response\_Abstract::sendHeaders() ignores sending headers if output already is sent to the browser (checked by headers\_sent()). where the behaviour is not totally wrong the result is very annoying because the method don't issues any errors that headers can't be send.

IMO the sendHeaders() method should throw an exception so that developers can see why i.e. a redirect doesn't work correctly. An alternative would be to implements a canSendHeaders() method in the abstract response and force the redirect to throw an exception. the latter makes exception with contextualized message possible.

 

 

### Comments

Posted by Matthew Weier O'Phinney (matthew) on 2007-02-08T11:02:52.000+0000

The biggest issue with this is how to test. When running the test suite, because the test runner is sending output continuously, headers are always sent -- which means that methods like sendHeaders (and, really, set(Raw)Header() and setRedirect()) would always throw exceptions in the test suite, and thus could not be tested easily.

My suggestion, then, is to have a flag that can be set that determines the behaviour. By default, it would be on, and exceptions would be thrown if headers have already been sent. If turned off, the methods would process as normal.

 

 

Posted by Matthew Weier O'Phinney (matthew) on 2007-02-08T11:17:28.000+0000

Resolved in revision 3300

 

 