---
layout: issue
title: "Throwing exception in template (and/or layout) doesnt fails gracefully"
id: ZF2-414
---

ZF2-414: Throwing exception in template (and/or layout) doesnt fails gracefully
-------------------------------------------------------------------------------

 Issue Type: Improvement Created: 2012-07-20T13:48:41.000+0000 Last Updated: 2012-10-08T20:15:06.000+0000 Status: Closed Fix version(s): 
 Reporter:  Marek Nos (fabicz)  Assignee:  Matthew Weier O'Phinney (matthew)  Tags: - Zend\\View
 
 Related issues: 
 Attachments: 
### Description

template.phtml

<? throw \\Exception('error');

shows: Fatal error: Uncaught exception 'Exception' with message 'error' in /path/to/template.phtml on line 2

I would expect to catch those exceptions and forward (eg by forward plugin) to 404 page.

 

 

### Comments

Posted by Matthew Weier O'Phinney (matthew) on 2012-07-20T15:15:22.000+0000

Why would you expect an exception in the view to lead to a 404 page? This makes no sense to me -- the route clearly was handled. If anything, I would expect a 500 page to occur. I'll mark this as a feature request for such functionality.

 

 

Posted by Matthew Weier O'Phinney (matthew) on 2012-07-20T15:16:36.000+0000

Not a critical issue, so downgrading to minor priority. Also modified issue type to "Improvement".

 

 

Posted by Marek Nos (fabicz) on 2012-07-20T20:09:53.000+0000

Correct, 500 page for sure.

But I see it as serious issue, because everyone who rely on lazyloading heavily, will run into exceptions just because everything is loaded once the Model classes are accessed in view layer. And also because there is no easy workaround how to emulate this by events. Or is there?

 

 

Posted by Ralph Schindler (ralph) on 2012-10-08T20:15:06.000+0000

This issue has been closed on Jira and moved to GitHub for issue tracking. To continue following the resolution of this issues, please visit: <https://github.com/zendframework/zf2/issues/2506>

 

 